// Möngö Savings — Phase 1C
// Pure goal/savings calculations, metadata and user-confirmed interest transaction construction.
(function(global){
'use strict';
const num=v=>Number(v)||0,MODES=new Set(['compound','payout','maturity','none']),FREQUENCIES=new Set(['monthly','quarterly','yearly','maturity']);
function transferContribution(goal,transfers){return (Array.isArray(transfers)?transfers:[]).filter(t=>t?.purpose==='savings'&&String(t.targetId)===String(goal?.id)).reduce((s,t)=>s+num(t.amount),0);}
function interestContribution(goal,txns){return (Array.isArray(txns)?txns:[]).filter(t=>t?.type==='income'&&t.incomePurpose==='savings_interest'&&String(t.goalId)===String(goal?.id)).reduce((s,t)=>s+num(t.amount),0);}
function autoSaved(goal,transfers,txns){return transferContribution(goal,transfers)+interestContribution(goal,txns);}
function effectiveSaved(goal,transfers,txns){return Math.max(0,num(goal?.saved))+autoSaved(goal,transfers,txns);}
function progressPct(goal,transfers,txns){const target=Math.max(0,num(goal?.target)),saved=Math.max(0,effectiveSaved(goal,transfers,txns));return target>0?Math.max(0,Math.min(100,Math.round(saved/target*100))):0;}
function addMonthsSafe(date,months){const d=new Date(date.getFullYear(),date.getMonth(),date.getDate(),12,0,0,0),day=d.getDate();d.setMonth(d.getMonth()+months);if(d.getDate()<day)d.setDate(0);return d;}
function monthsBetweenCeil(from,to){const start=new Date(from.getFullYear(),from.getMonth(),from.getDate(),12,0,0,0),end=new Date(to.getFullYear(),to.getMonth(),to.getDate(),12,0,0,0);if(end<=start)return 0;let months=(end.getFullYear()-start.getFullYear())*12+(end.getMonth()-start.getMonth());if(addMonthsSafe(start,months)<end)months++;return Math.max(0,months);}
function calendarMonthsDaysBetween(from,to){const start=new Date(from.getFullYear(),from.getMonth(),from.getDate(),12,0,0,0),end=new Date(to.getFullYear(),to.getMonth(),to.getDate(),12,0,0,0);if(end<=start)return {months:0,days:0};let months=(end.getFullYear()-start.getFullYear())*12+(end.getMonth()-start.getMonth()),anchor=addMonthsSafe(start,months);if(anchor>end){months=Math.max(0,months-1);anchor=addMonthsSafe(start,months);}return {months,days:Math.max(0,Math.round((end-anchor)/86400000))};}
function normalizeInterestMetadata(input){const x=input||{},mode=MODES.has(x.interestMode)?x.interestMode:'compound',frequency=FREQUENCIES.has(x.interestFrequency)?x.interestFrequency:'monthly';return {interestMode:mode,annualInterestRate:Math.max(0,num(x.annualInterestRate)),interestFrequency:frequency,interestAccountId:x.interestAccountId||null,linkedGoalId:x.linkedGoalId||null,maturityDate:x.maturityDate||''};}
function interestDestination(account,defaultAccountId){if(!account||account.interestMode==='none')return null;return account.interestMode==='payout'?(account.interestAccountId||defaultAccountId||null):(account.id||null);}
function linkedGoalId(account){return account?.linkedGoalId||account?.goalId||null;}
function makeInterestTransaction(input,options={}){const x=input||{},amount=Math.round(num(x.amount));if(!(amount>0))return {ok:false,reason:'amount_required'};if(!x.date)return {ok:false,reason:'date_required'};if(!x.accountId)return {ok:false,reason:'account_required'};if(!x.savingsAccountId)return {ok:false,reason:'savings_account_required'};return {ok:true,transaction:{id:x.id||options.id||null,type:'income',desc:x.desc||'',catKey:x.catKey||null,catName:x.catName||'',subcatName:x.subcatName||'',amount,date:x.date,accountId:x.accountId,savingsInterest:true,savingsAccountId:x.savingsAccountId,interestMode:x.interestMode||'compound',incomePurpose:'savings_interest',goalId:x.goalId||null,createdAt:x.createdAt||options.timestamp||new Date().toISOString()}};}
global.MongoSavings=Object.freeze({transferContribution,interestContribution,autoSaved,effectiveSaved,progressPct,addMonthsSafe,monthsBetweenCeil,calendarMonthsDaysBetween,normalizeInterestMetadata,interestDestination,linkedGoalId,makeInterestTransaction});
})(window);
