// Möngö Audit — Phase 1C
// Pure cross-feature invariant findings only. Never mutates or auto-fixes financial data.
(function(global){
'use strict';
const num=v=>Number(v)||0, id=v=>String(v==null?'':v);
function finding(code,severity,details){return {code,severity:severity||'error',...(details||{})};}
function duplicateIds(rows){const seen=new Set(),dupes=new Set();(rows||[]).forEach(r=>{const k=id(r&&r.id);if(!k)return;if(seen.has(k))dupes.add(k);seen.add(k);});return [...dupes];}
function ledgerIdFindings(ledger,expectedIds){const rows=Array.isArray(ledger)?ledger:[],actual=new Set(rows.map(r=>id(r&&r.id)).filter(Boolean)),out=[];duplicateIds(rows).forEach(x=>out.push(finding('duplicate-ledger-id','error',{id:x})));(expectedIds||[]).map(id).filter(Boolean).forEach(x=>{if(!actual.has(x))out.push(finding('missing-ledger-id','error',{id:x}));});return out;}
function sourceLedgerIds(input){const x=input||{},ids=[];(x.txns||[]).filter(t=>t&&!t.loanPaymentId&&(t.type==='income'||t.type==='expense')).forEach(t=>ids.push('txn:'+id(t.id)));(x.transfers||[]).forEach(t=>ids.push('transfer:'+id(t.id)));(x.debts||[]).forEach(d=>{if(d&&d.fundingMode==='existing'&&num(d.fundingAmount)>0&&d.fundingAccountId)ids.push('loan-received:'+id(d.id));(Array.isArray(d&&d.payments)?d.payments:[]).forEach(p=>ids.push('loan-payment:'+id(p.id)));});return ids;}
function sourceLedgerParityFindings(input){const x=input||{},expected=sourceLedgerIds(x),expectedSet=new Set(expected),out=ledgerIdFindings(x.ledger,expected);(x.ledger||[]).forEach(e=>{const lid=id(e&&e.id);if(!lid)return;if(/^(txn:|transfer:|loan-received:|loan-payment:)/.test(lid)&&!expectedSet.has(lid))out.push(finding('orphan-ledger-row','warn',{ledgerId:lid,kind:e&&e.kind}));});return out;}
function transferFindings(transfers){const out=[];(transfers||[]).forEach(t=>{const tid=id(t&&t.id),from=id(t&&t.fromId),to=id(t&&t.toId),amount=num(t&&t.amount);if(!from||!to)out.push(finding('transfer-missing-account','error',{id:tid,fromId:from,toId:to}));if(from&&to&&from===to)out.push(finding('transfer-same-account','error',{id:tid,accountId:from}));if(amount<=0)out.push(finding('transfer-nonpositive-amount','error',{id:tid,amount}));});return out;}
function accountReferenceFindings(accounts,ledger){const known=new Set((accounts||[]).map(a=>id(a&&a.id)).filter(Boolean)),out=[];(ledger||[]).forEach(e=>{[['fromAccountId','ledger-unknown-from-account'],['toAccountId','ledger-unknown-to-account']].forEach(([field,code])=>{const aid=id(e&&e[field]);if(aid&&!known.has(aid))out.push(finding(code,'error',{ledgerId:id(e&&e.id),accountId:aid}));});});return out;}
function ledgerDeltaForAccount(accountId,ledger){const aid=id(accountId);return (ledger||[]).reduce((sum,e)=>sum+(id(e&&e.toAccountId)===aid?num(e.amount):0)-(id(e&&e.fromAccountId)===aid?num(e.amount):0),0);}
function accountBalanceFindings(accounts,ledger,balanceFor){if(typeof balanceFor!=='function')return [];const out=[];(accounts||[]).forEach(a=>{const aid=id(a&&a.id),opening=num(a&&a.openingBalance),delta=ledgerDeltaForAccount(aid,ledger),expected=opening+delta,actual=num(balanceFor(aid));if(Math.abs(actual-expected)>1)out.push(finding('account-balance-ledger-mismatch','error',{accountId:aid,opening,ledgerDelta:delta,expected,actual}));});return out;}
function transferConservationFindings(transfers){const out=[];(transfers||[]).forEach(t=>{const tid=id(t&&t.id),from=id(t&&t.fromId),to=id(t&&t.toId),amount=num(t&&t.amount);if(!from||!to||from===to||amount<=0)return;const sourceDelta=-amount,destinationDelta=amount,net=sourceDelta+destinationDelta;if(Math.abs(net)>1e-9)out.push(finding('transfer-conservation-failed','error',{id:tid,sourceDelta,destinationDelta,net}));});return out;}
function loanSplitFindings(ledger){const out=[];(ledger||[]).filter(e=>e&&e.kind==='loan_payment').forEach(e=>{const total=num(e.amount),split=num(e.principal)+num(e.interest)+num(e.extraPrincipal);if(Math.abs(total-split)>1)out.push(finding('loan-payment-split-mismatch','error',{ledgerId:id(e.id),total,split}));});return out;}
function legacyLoanTxnFindings(txns){return (txns||[]).filter(t=>t&&t.loanPaymentId).map(t=>finding('loan-payment-duplicate-txn-signal','warn',{txnId:id(t.id),loanPaymentId:id(t.loanPaymentId)}));}
function savingsDoubleCountFindings(txns,transfers){const moved=new Set((transfers||[]).filter(t=>t&&t.purpose==='savings').map(t=>id(t.targetId)).filter(Boolean));return (txns||[]).filter(t=>t&&t.type==='expense'&&moved.has(id(t.goalId||t.targetId))&&(t.purpose==='savings'||t.expensePurpose==='savings')).map(t=>finding('savings-transfer-expense-double-count-signal','warn',{txnId:id(t.id),goalId:id(t.goalId||t.targetId)}));}
function run(input){const x=input||{},out=[];out.push(...sourceLedgerParityFindings(x));out.push(...transferFindings(x.transfers));out.push(...accountReferenceFindings(x.accounts,x.ledger));out.push(...accountBalanceFindings(x.accounts,x.ledger,x.balanceFor));out.push(...transferConservationFindings(x.transfers));out.push(...loanSplitFindings(x.ledger));out.push(...legacyLoanTxnFindings(x.txns));out.push(...savingsDoubleCountFindings(x.txns,x.transfers));return out;}
global.MongoAudit=Object.freeze({finding,duplicateIds,ledgerIdFindings,sourceLedgerIds,sourceLedgerParityFindings,transferFindings,accountReferenceFindings,ledgerDeltaForAccount,accountBalanceFindings,transferConservationFindings,loanSplitFindings,legacyLoanTxnFindings,savingsDoubleCountFindings,run});
})(window);
